# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 986c0e86a030e770157b1bc8f9163251d3990f6b58f16eba5a4885907b46e892d633ffe7d59e571062b73d04d96c74b1427736c1f85f2c5a8a74c59aa565b7b0

test:
  secret_key_base: e30aaa12f463ce6d44e867615638862b7aae8ebc194a96ad1b10657d4bd6d9bad338ace6871ff3f9b2cf6f3383d44b62bd732aa83d50adffd912e8d4c8bd175d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
